#!/bin/bash

set -e

# Test
if [ "$1" = "test" ]; then
    # Generate dependencies
    make depend

    # Run tests
    make test

    exit 0
fi

# Go
if [ "$1" = "go" ]; then
    # Install native dependencies
    apt update
    apt install -y curl make

    # Install bagop
    curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
    install /tmp/bagop /usr/local/bin

    # Generate dependencies
    make depend

    # Build
    CGO_ENABLED=0 bagop -j "$(nproc)" -b weron -x '(android/*|ios/*|plan9/*|aix/*|js/wasm)' -p 'make build/weron DST=$DST' -d out

    exit 0
fi
