name: Docker CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project:
          - src: .
            image: ghcr.io/pojntfx/weron
            arch: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/ppc64le,linux/riscv64,linux/s390x"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.project.image }}
          tags: type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.project.src }}
          file: ${{ matrix.project.src }}/Dockerfile
          platforms: ${{ matrix.project.arch }}
          push: false
          tags: ${{ matrix.project.image }}:unstable
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push pre-release image to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.project.src }}
          file: ${{ matrix.project.src }}/Dockerfile
          platforms: ${{ matrix.project.arch }}
          push: true
          tags: ${{ matrix.project.image }}:unstable
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push release image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.project.src }}
          file: ${{ matrix.project.src }}/Dockerfile
          platforms: ${{ matrix.project.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
